### PR TITLE
feature(website): specific pages for each video

### PR DESCRIPTION
**Pull request by ssandino**
Draft for video pages

### CODE REVIEW

**Comment by ssandino** [comment]
@mkue, thanks for the review. I've created individual pages for each video, allowing us to add metadata per page. However, I've consolidated all translations into one file since they are mostly identical or very similar, particularly in terms of video credits.

File: shared/locales/de/website-videos.json [hunk 1]
```diff
@@ -0,0 +1,80 @@
+{
+	"credits": "Credits",
+	"id": {
+		"video-01": "896169775",
+		"video-02": "488184818",
+		"video-03": "840215695"
+	},
+	"video-01": {
+		"credits": [
+			{
```
Comment (mkue) [inline shared/locales/de/website-videos.json:10]: If you added the credits here, it makes sense to remove them from the old location. Otherwise, we have the same information twice...

Comment (ssandino) [reply shared/locales/de/website-videos.json:10]: @mkue Good point. I deleted the duplicated credits.

**Comment by mkue** [comment]
Looks good now🙌🏼

**Review by mkue — APPROVED** [review]

File: website/src/app/[lang]/[region]/(website)/(home)/(sections)/video.tsx [hunk 2]
```diff
@@ -16,30 +16,28 @@ import {
...
 							<TableBody>
-								{translator
-									.t<{ role: string; name: string }[]>('video.credits-content')
-									.map(({ role, name }, index) => (
-										<TableRow key={index}>
-											<TableCell className="p-1.5 font-medium">{role}</TableCell>
-											<TableCell className="p-1.5">{name}</TableCell>
-										</TableRow>
-									))}
+								{translator.t<{ role: string; name: string }[]>('video-01.credits').map(({ role, name }, index) => (
```
Comment (andrashee) [inline website/src/app/[lang]/[region]/(website)/(home)/(sections)/video.tsx:35]: Since merging the latest main into my campaign branch, I get the following error when calling `http://localhost:3001` (which redirects me to `http://localhost:3001/en/ch`):

image

```
 src/app/[lang]/[region]/(website)/(home)/(sections)/video.tsx (38:76) @ map
 ⨯ TypeError: translator.t(...).map is not a function
    at Video (video.tsx:66:80)
digest: "791144539"
  36 |                                          <Table>
  37 |                                                  <TableBody>
> 38 |                                                          {translator.t<{ role: string; name: string }[]>('video-01.credits').map(({ role, name }, index) => (
     |                                                                                                                             ^
  39 |                                                                  <TableRow key={index}>
  40 |                                                                          <TableCell className="p-1.5 font-medium">{role}</TableCell>
  41 |                                                                          <TableCell className="p-1.5">{name}</TableCell>
```

Seems like `translator.t<{ role: string; name: string }[]>('video-01.credits')` resolves to `undefined`.

Comment (ssandino) [reply website/src/app/[lang]/[region]/(website)/(home)/(sections)/video.tsx:35]: @anthonyray had the same issue and mentioned it in a [Slack message](https://socialincome.slack.com/archives/C040MU2HHT8/p1707923501262169). 

The [proposed solution](https://socialincome.slack.com/archives/C040MU2HHT8/p1708076278056079):

> Erasing the website' `.next` folder and running `npm install` and `npm run website:serve `

might have fixed it – at least it got a 👍🏻 from @anthonyray (maybe it was also just to say thanks for the possible solution and it didn't do anything). Worth trying out.

Comment (andrashee) [reply website/src/app/[lang]/[region]/(website)/(home)/(sections)/video.tsx:35]: That indeed fixed it. Great stuff, thanks @ssandino
